### ISSUE TITLE
Deletion of `ui-builder` branch in ReplPad master

### ISSUE THREAD

**Issue by hostilefork** [BrianOtto/ui-builder#2]
Presumably it's no longer needed, but didn't want to delete it in case there was some bit of it that was important:

https://github.com/hostilefork/replpad-js/branches

If possible, I'd like PRs to be done from branches that are from people's personal repositories...that way, the responsibility stays on them...

*(Bad example here--given this is something I started in my own repo and grew, so my enlistment IS the master.  I just haven't been sending PRs for review to myself yet (!).  But I'll migrate it out at some point, as it's becoming a group effort.)*

**Comment by BrianOtto** [comment]
Done. There was nothing needed in the branch. I just hadn't gotten around to deleting it yet.
